/**
 * AI Decision Disclosure (US-1010)
 *
 * Malaysia PDPA 2025 (PCP 3/2025) — Right to refuse automated AI decisions
 * and request human review.
 *
 * When Rainbow AI makes a material automated decision (booking suggestion,
 * escalation trigger, order confirmation), the guest must receive:
 *   1. A disclosure that the decision was AI-generated
 *   2. A quick-reply button (or text prompt) to request human review
 *
 * This module provides:
 *   - `MATERIAL_DECISION_TYPES` — set of decision types requiring disclosure
 *   - `logAiDecision()` — create an audit record for an AI decision
 *   - `updateAiDecisionOutcome()` — update outcome when resolved
 *   - `isHumanReviewRequest()` — detect "human" keyword or quick-reply
 *   - `getDisclosureTemplate()` — retrieve per-profile disclosure message
 *   - `getAiDecisionAuditLog()` — query audit records for admin
 */

import { pool } from './db.js';

// ─── Constants ───────────────────────────────────────────────────────────────

/** Decision types that require AI disclosure under PDPA 2025 PCP 3/2025 */
export const MATERIAL_DECISION_TYPES = new Set([
  'booking',           // Room booking suggestion / confirmation
  'escalation',        // AI-triggered escalation to human staff
  'order_confirmation',// Food order placed via AI assistant
  'menu_recommendation', // Personalised menu recommendation
]);

/** Keywords that trigger human review request detection */
const HUMAN_REVIEW_KEYWORDS = ['human', 'staff', 'person', 'agent', 'manusia', 'orang'];

// ─── Default Disclosure Template ─────────────────────────────────────────────

export const DEFAULT_DISCLOSURE_TEMPLATE =
  'This recommendation was generated by Rainbow AI (automated system). ' +
  'Reply *human* at any time to request a human staff review before this action is finalised.';

// ─── Database helpers ────────────────────────────────────────────────────────

let _tableEnsured = false;

/** Test-only: reset table-ensured flag so each test starts fresh. */
export function _resetTableEnsured(): void { _tableEnsured = false; }

async function ensureTable(): Promise<void> {
  if (_tableEnsured) return;
  try {
    await pool.query(`
      CREATE TABLE IF NOT EXISTS ai_decision_audit (
        id SERIAL PRIMARY KEY,
        profile_id TEXT NOT NULL DEFAULT 'pelangi',
        phone VARCHAR(64) NOT NULL,
        decision_type VARCHAR(64) NOT NULL,
        intent TEXT,
        confidence_score REAL,
        ai_provider TEXT,
        human_review_requested BOOLEAN NOT NULL DEFAULT FALSE,
        outcome VARCHAR(64),
        disclosure_sent_at TIMESTAMPTZ,
        review_requested_at TIMESTAMPTZ,
        resolved_at TIMESTAMPTZ,
        metadata TEXT,
        created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
      )
    `);
    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_aidecision_profile_phone ON ai_decision_audit (profile_id, phone)
    `);
    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_aidecision_created_at ON ai_decision_audit (created_at DESC)
    `);
    await pool.query(`
      CREATE INDEX IF NOT EXISTS idx_aidecision_human_review ON ai_decision_audit (human_review_requested)
    `);
    _tableEnsured = true;
  } catch (err: any) {
    console.warn('[AiDisclosure] Table ensure failed (non-fatal):', err.message);
  }
}

// ─── Core API ────────────────────────────────────────────────────────────────

export interface AiDecisionRecord {
  id: number;
  profileId: string;
  phone: string;
  decisionType: string;
  intent: string | null;
  confidenceScore: number | null;
  aiProvider: string | null;
  humanReviewRequested: boolean;
  outcome: string | null;
  disclosureSentAt: Date | null;
  reviewRequestedAt: Date | null;
  resolvedAt: Date | null;
  metadata: Record<string, unknown> | null;
  createdAt: Date;
}

export interface LogAiDecisionInput {
  profileId: string;
  phone: string;
  decisionType: string;
  intent?: string;
  confidenceScore?: number;
  aiProvider?: string;
  disclosureSent?: boolean;
  metadata?: Record<string, unknown>;
}

/**
 * Create an audit record for an AI-generated decision.
 * Returns the new record ID (useful for updating outcome later).
 */
export async function logAiDecision(input: LogAiDecisionInput): Promise<number> {
  try {
    await ensureTable();
    const result = await pool.query<{ id: number }>(
      `INSERT INTO ai_decision_audit
        (profile_id, phone, decision_type, intent, confidence_score, ai_provider,
         disclosure_sent_at, metadata)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
       RETURNING id`,
      [
        input.profileId,
        input.phone,
        input.decisionType,
        input.intent ?? null,
        input.confidenceScore ?? null,
        input.aiProvider ?? null,
        input.disclosureSent ? new Date() : null,
        input.metadata ? JSON.stringify(input.metadata) : null,
      ]
    );
    return result.rows[0]?.id ?? 0;
  } catch (err: any) {
    console.warn('[AiDisclosure] logAiDecision failed (non-fatal):', err.message);
    return 0;
  }
}

/**
 * Update the outcome of an AI decision audit record.
 * Call this when the decision is resolved (accepted / human_review / cancelled).
 */
export async function updateAiDecisionOutcome(
  id: number,
  outcome: 'accepted' | 'human_review' | 'escalated' | 'cancelled',
  humanReviewRequested?: boolean
): Promise<void> {
  if (!id) return;
  try {
    await ensureTable();
    await pool.query(
      `UPDATE ai_decision_audit
       SET outcome = $1,
           resolved_at = NOW(),
           human_review_requested = COALESCE($2, human_review_requested),
           review_requested_at = CASE WHEN $2 = TRUE THEN NOW() ELSE review_requested_at END
       WHERE id = $3`,
      [outcome, humanReviewRequested ?? null, id]
    );
  } catch (err: any) {
    console.warn('[AiDisclosure] updateAiDecisionOutcome failed (non-fatal):', err.message);
  }
}

/**
 * Check if a guest message is a human review request.
 * Matches "human", "staff", "person", "agent" and Malay equivalents,
 * as well as the WhatsApp quick-reply payload "REQUEST_HUMAN_REVIEW".
 */
export function isHumanReviewRequest(text: string, payload?: string): boolean {
  if (payload === 'REQUEST_HUMAN_REVIEW') return true;
  const normalized = text.trim().toLowerCase();
  return HUMAN_REVIEW_KEYWORDS.some(kw => normalized === kw || normalized.startsWith(kw + ' '));
}

/**
 * Retrieve the disclosure message template for a given profile.
 * Falls back to DEFAULT_DISCLOSURE_TEMPLATE if not configured.
 */
export async function getDisclosureTemplate(profileId: string): Promise<string> {
  try {
    const result = await pool.query<{ value: string }>(
      `SELECT value FROM app_settings WHERE key = $1`,
      [`ai_disclosure_template_${profileId}`]
    );
    if (result.rows.length > 0 && result.rows[0].value) {
      return result.rows[0].value;
    }
    // Try generic key
    const generic = await pool.query<{ value: string }>(
      `SELECT value FROM app_settings WHERE key = 'ai_disclosure_template'`
    );
    if (generic.rows.length > 0 && generic.rows[0].value) {
      return generic.rows[0].value;
    }
  } catch (err: any) {
    console.warn('[AiDisclosure] getDisclosureTemplate failed (non-fatal):', err.message);
  }
  return DEFAULT_DISCLOSURE_TEMPLATE;
}

/**
 * Save a per-profile disclosure template to app_settings.
 */
export async function saveDisclosureTemplate(profileId: string, template: string): Promise<void> {
  await pool.query(
    `INSERT INTO app_settings (key, value, description)
     VALUES ($1, $2, $3)
     ON CONFLICT (key) DO UPDATE SET value = $2, updated_at = NOW()`,
    [
      `ai_disclosure_template_${profileId}`,
      template,
      `PDPA 2025 AI disclosure message template for profile: ${profileId}`,
    ]
  );
}

/**
 * Query AI decision audit log for admin panel.
 */
export interface AuditQueryOptions {
  profileId?: string;
  phone?: string;
  decisionType?: string;
  humanReviewOnly?: boolean;
  limit?: number;
  offset?: number;
}

export async function getAiDecisionAuditLog(
  options: AuditQueryOptions = {}
): Promise<AiDecisionRecord[]> {
  try {
    await ensureTable();
    const conditions: string[] = [];
    const params: unknown[] = [];
    let paramIdx = 1;

    if (options.profileId) {
      conditions.push(`profile_id = $${paramIdx++}`);
      params.push(options.profileId);
    }
    if (options.phone) {
      conditions.push(`phone = $${paramIdx++}`);
      params.push(options.phone);
    }
    if (options.decisionType) {
      conditions.push(`decision_type = $${paramIdx++}`);
      params.push(options.decisionType);
    }
    if (options.humanReviewOnly) {
      conditions.push(`human_review_requested = TRUE`);
    }

    const where = conditions.length > 0 ? `WHERE ${conditions.join(' AND ')}` : '';
    const limit = options.limit ?? 50;
    const offset = options.offset ?? 0;

    const result = await pool.query<{
      id: number; profile_id: string; phone: string; decision_type: string;
      intent: string | null; confidence_score: number | null; ai_provider: string | null;
      human_review_requested: boolean; outcome: string | null;
      disclosure_sent_at: Date | null; review_requested_at: Date | null;
      resolved_at: Date | null; metadata: string | null; created_at: Date;
    }>(
      `SELECT * FROM ai_decision_audit ${where}
       ORDER BY created_at DESC
       LIMIT $${paramIdx++} OFFSET $${paramIdx++}`,
      [...params, limit, offset]
    );

    return result.rows.map(r => ({
      id: r.id,
      profileId: r.profile_id,
      phone: r.phone,
      decisionType: r.decision_type,
      intent: r.intent,
      confidenceScore: r.confidence_score,
      aiProvider: r.ai_provider,
      humanReviewRequested: r.human_review_requested,
      outcome: r.outcome,
      disclosureSentAt: r.disclosure_sent_at,
      reviewRequestedAt: r.review_requested_at,
      resolvedAt: r.resolved_at,
      metadata: r.metadata ? JSON.parse(r.metadata) : null,
      createdAt: r.created_at,
    }));
  } catch (err: any) {
    console.warn('[AiDisclosure] getAiDecisionAuditLog failed (non-fatal):', err.message);
    return [];
  }
}

/**
 * Get summary stats for AI decision audit (for admin dashboard widget).
 */
export async function getAiDecisionStats(profileId: string): Promise<{
  total: number;
  humanReviewRequested: number;
  humanReviewRate: number;
  byDecisionType: Record<string, number>;
}> {
  try {
    await ensureTable();
    const result = await pool.query<{
      total: string; human_review: string;
    }>(
      `SELECT
         COUNT(*) AS total,
         SUM(CASE WHEN human_review_requested THEN 1 ELSE 0 END) AS human_review
       FROM ai_decision_audit WHERE profile_id = $1`,
      [profileId]
    );
    const row = result.rows[0];
    const total = parseInt(row?.total ?? '0', 10);
    const humanReview = parseInt(row?.human_review ?? '0', 10);

    const byTypeResult = await pool.query<{ decision_type: string; count: string }>(
      `SELECT decision_type, COUNT(*) AS count
       FROM ai_decision_audit WHERE profile_id = $1
       GROUP BY decision_type`,
      [profileId]
    );
    const byDecisionType: Record<string, number> = {};
    for (const r of byTypeResult.rows) {
      byDecisionType[r.decision_type] = parseInt(r.count, 10);
    }

    return {
      total,
      humanReviewRequested: humanReview,
      humanReviewRate: total > 0 ? Math.round((humanReview / total) * 100) / 100 : 0,
      byDecisionType,
    };
  } catch (err: any) {
    console.warn('[AiDisclosure] getAiDecisionStats failed (non-fatal):', err.message);
    return { total: 0, humanReviewRequested: 0, humanReviewRate: 0, byDecisionType: {} };
  }
}
